// use o plugin bnf do vscode para melhor visualizar
"Start Symbol" = <S>
<S> ::= <DEC> '.' <A> | <ATR> '.' <A> | <REP> <A> | <COND> <A>
<A> ::= <DEC> '.' <A> | <ATR> '.' <A> | <REP> <A> | <COND> <A> | <>
<RVAR> ::= VAR
<DEC> ::= BIN <RVAR> | BIN <RVAR> '~' NUM
<ATR> ::= <RVAR> '~' NUM
<OP> ::= IGUAL | MAIOR | MENOR
<COND> ::= SE <CONDS> '{' <S> '}'
<REP> ::= ENQUANTO <CONDS> '{' <S> '}'
<CONDS> ::= <RVAR> | <RVAR> <OP> <RVAR> | <RVAR> <OP> NUM | NUM <OP> <RVAR> | NUM <OP> NUM
